// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCchJD33RdoQEda1m4JudNn6ZH8tfhfL4Q',
    appId: '1:343376983772:web:0f39dd9d00cefe668ae619',
    messagingSenderId: '343376983772',
    projectId: 'igeo-90933',
    authDomain: 'igeo-90933.firebaseapp.com',
    storageBucket: 'igeo-90933.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmWfA1OIolnpYCTgSsb3o9sm83U55YG7g',
    appId: '1:343376983772:android:dfc40850a6b6c8c88ae619',
    messagingSenderId: '343376983772',
    projectId: 'igeo-90933',
    storageBucket: 'igeo-90933.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIPaRTQtFDM3qSSsAl_g84J6b79kXXFkE',
    appId: '1:343376983772:ios:19f9e39fb774e5a18ae619',
    messagingSenderId: '343376983772',
    projectId: 'igeo-90933',
    storageBucket: 'igeo-90933.firebasestorage.app',
    iosBundleId: 'com.example.igeo',
  );
}
